version: "2"

services:
  central_server:
    restart: always
    build: ./central_server/
    ports:
      - "8080:80"
    environment:
      - HYDRUS_SERVER_URL=http://central_server/ ## For linux local
      # - HYDRUS_SERVER_URL=http://192.168.99.100:8080/ ## For windows 10
      # - HYDRUS_SERVER_URL=http://54.169.232.177:8080/
      # - SERVER_URL=http://localhost:8080/
      - API_NAME=serverapi
      - DB_URL=postgresql://hydra:hailhydra@postgres_db:5432/hydrus

    networks:
      main:
        aliases:
          - central_server


  postgres:
    restart: always
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=hailhydra
      - POSTGRES_DB=hydrus
    image: postgres:latest
    ports:
      - "9000:5432"
    networks:
      main:
        aliases:
          - postgres_db


  drone1:
    restart: always
    build: ./drone1/
    ports:
      - "8081:80"
    environment:
      - HYDRUS_SERVER_URL=http://drone1/ ## For linux local
      # - HYDRUS_SERVER_URL=http://192.168.99.100:8081/ ## For windows 10
      # - HYDRUS_SERVER_URL=http://54.169.232.177:8081/
      # - SERVER_URL=http://localhost:8081/
      - API_NAME=droneapi
      # Will use in sqlite db
      # - DB_URL=postgresql://hydra:hailhydra@postgres_db:5432/hydrus

    networks:
      main:
        aliases:
          - drone1
  #
  # drone2:
  #   restart: always
  #   build: ./drone2/
  #   ports:
  #     - "8082:80"
  #   environment:
  #     # - HYDRUS_SERVER_URL=http://localhost:8082/ ## For linux local
  #     - HYDRUS_SERVER_URL=http://192.168.99.100:8082/ ## For windows 10
  #     # - HYDRUS_SERVER_URL=http://54.169.232.177:8082/
  #   networks:
  #     main:
  #       aliases:
  #         - drone2

networks:
  main:
